config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  root 'places#index'

  resources :places do
    resources :comments, only:  :create
    resources :photos, only: :create
  end 

  resources :users, only: :show

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  # designates that Comment is tied to user and place. 
  belongs_to :user
  belongs_to :place
  after_create :send_comment_email

  RATINGS = {
    'one star' => '1_star', 
    'two stars' => '2_stars',
    'three stars' => '3_stars',
    'four stars' => '4_stars',
    'five stars' => '5_stars'
  }

  def humanized_rating
    RATINGS.invert[self.rating]
  end

  def send_comment_email
    NotificationMailer.comment_added(self).deliver
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  belongs_to :place
  mount_uploader :picture, PictureUploader

  validates :picture, :caption, presence: true
end

app/models/place.rb
class Place < ActiveRecord::Base
  belongs_to :user 
  # designates that the Place can have many comments tied to it. 
  has_many :comments
  has_many :photos

  # Geocode
  geocoded_by :address
  after_validation :geocode # auto fetch cooridinates

  # Checks if a data is present in each form field before the data is submitted
  # Also checks if the length meets the requirments 
  validates :description, :address, :name, presence: true, length: {minimum: 3}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :places
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # Checks to see if the user is logged in before running any of this
  before_action :authenticate_user!
  def create
    @place =Place.find(params[:place_id])
    # Addes the ability to create a comment, also checks the comment params method
    # The current user is also merged into the params hash 
    @place.comments.create(comment_params.merge(user: current_user))
    redirect_to place_path(@place)
  end 

  private

  def comment_params
    params.require(:comment).permit(:message, :rating)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # Checks to see if the user is logged in before running any of this
  before_action :authenticate_user!
  def create
    @place =Place.find(params[:place_id])
    if @place.user != current_user
      return render text: "Not Allowed", status: :forbidden
    end

    @photo = @place.photos.build(photo_params)

    if @photo.save
      flash[:notice] = "You did it!!!!!"
    else
      flash[:error] = ""
    end 

    redirect_to place_path(@place)
  end 

  private

  def photo_params
    params.require(:photo).permit(:caption, :picture)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  # Checks before a certain rails action occurs.
  # In this case it only checks if a user is logged in.
  # You can find these action suffixes using "rake routes" :party_parrot:
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :delete]

  def index
    @places = Place.paginate(:page => params[:page], :per_page => 5)
  end

  def new
    @place = Place.new
  end

  def create
    @place = current_user.places.create(place_params)
    # checks if the place has been validated
    if @place.valid?
      redirect_to root_path
    else 
      # if it hasn't then adds an error message, simple_form helps deal with it. 
      render :new, status: :unprocessable_entity
    end 
  end

  def show
    # Querries the Place database to find a "place" with a certain id and assigns it to @place
    @place = Place.find(params[:id])
    @comment = Comment.new
    @photo = Photo.new 
  end

  def edit
    @place = Place.find(params[:id])

    # Forbids users from editing other user's places
    if @place.user != current_user
      return render text: 'Not Allowed', status: :forbidden
    end
  end

  def update
    @place = Place.find(params[:id])
    if @place.user != current_user
      return render text: "Not allowed", status: :forbidden
    end

    @place.update_attributes(place_params)
    if @place.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @place = Place.find(params[:id])
    if @place.user != current_user
      return render text: "Not Allowed", status: :forbidden
    end 

    @place.destroy
    redirect_to root_path
  end

  private

  def place_params
    params.require(:place).permit(:name, :description, :address)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show 
    # pulls the id from the url then queries the User table for the current user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do 
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message 
            end)
    end
    nil
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Nomster</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Nomster', root_path, class: 'navbar-brand' %> 
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li>
            <%= link_to new_place_path do %> 
              <i class="glyphicon glyphicon-plus"></i>
              New Place
            <% end %>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li> <%= link_to "User Profile", user_path(current_user) %> </li>
            <li> <%= link_to 'Sign out', destroy_user_session_path, method: :delete %> </li>
          <% else %>
            <li> <%= link_to 'Sign in', new_user_session_path %> </li>
            <li> <%= link_to 'Sign up', new_user_registration_path %> </li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

<%= yield %>

<% if notice.present? %>
  <p class="alert alert-info col-xs-10 col-xs-offset-1"><%= notice %></p>
<% end %>
<% if alert.present? %>
  <p class="alert alert-danger col-xs-10 col-xs-offset-1"><%= alert %></p>      
<% end %>

</body>
</html>

app/views/places/edit.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Edit Your Place</h1>
  <br>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br>
    <%= f.submit 'Update', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/places/index.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag "slider1.jpg", class: "img-responsive" %>
      <div class="carousel-caption">
        Find the best grease buckets
      </div>
    </div>
    <div class="item">
      <%= image_tag "slider2.jpg", class: "img-responsive" %>
      <div class="carousel-caption">
        Looking for that taste fix?
      </div>
    </div>
    <div class="item">
      <%= image_tag "slider3.jpg", class: "img-responsive" %>
      <div class="carousel-caption">
        One way ticket to flavor town
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>

<% @places.each do |place| %>
  <div class="booyah-box col-xs-10 col-xs-offset-1">
    <h1><%= link_to place.name, place_path(place) %></h1>
    <i><%= place.address %></i><br /> <br />
    <p><%= place.description %></p> <br /> 


    <% if place.comments.present? %>
      <div class="col-xs-12">
        <blockquote>
          <% if place.comments.last.humanized_rating.present? %>
            <b><%= place.comments.last.humanized_rating %></b> -
          <% end %>
          <%= place.comments.last.message %>
          <small><%= place.comments.last.user.email %></small>
        </blockquote>
      </div>
    <% end %>

    <% if place.photos.present? %>
      <div class="col-xs-12">
        <%= image_tag place.photos.first.picture %>
      </div>
    <% end %>

    <div class="clear"></div>
    <br>

    <% if place.user.present? %>
      <small> <%= place.user.email %> </small>
    <% end %>

  </div>
<% end %>

<div class="pagination-container col-xs-10 col-xs-offset-1">
  <%= will_paginate @places, renderer: BootstrapPagination::Rails %>
</div>

app/views/places/new.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Enter Your Place Details</h1>
  <br>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br>
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/places/show.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">

  <!-- References to the place object created in the controller. pulling from database -->
  <h1> <%= @place.name %> </h1>
  <i> <%= @place.address %> </i>
  <br><br>
  <p> <%= @place.description %> </p>

  <!-- Google Maps API -->
  <% if @place.latitude.present? && @place.longitude.present? %>
    <script>

      function initMap() {
        // Uses the latitude and longitude entries in the Place table
        var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 12,
          center: myLatLng
        });

        var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: 'Hello World!'
        });
      }
    </script>
    <!-- uses the key I generated with google api's -->
    <!-- Check out "google maps example" for finding sample google maps JS integration -->
    <script async defer
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA8XT4uva7mqQWvwixqZaKUfOPKTKOPeu0&callback=initMap">
    </script>

    <br>

    <div id="map"></div>
  <% end %>

  <br>

  <div class="pull-right">
    <!-- Uses logic to check if there is a current user and if the current user matches this place's user. If both true it allows access to the edit button. -->
    <% if current_user && current_user == @place.user %>
      <%= link_to 'Edit', edit_place_path(@place), class: 'btn btn-primary' %>
      <%= link_to 'Delete', place_path(@place), method: :delete, data: {confirm: "Are you sure you want to delete this?"}, class: "btn btn-danger" %>
    <% end %>
  </div>

</div>
<div class="clear"></div>


<!-- Photos -->

<!-- Modal -->
<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Add a picture</h4>
      </div>
      <div class="modal-body">
        <!-- the comments are now wired up underneath the place area in the routes.rb file -->
       <%= simple_form_for @photo, url: place_photos_path(@place) do |f| %>
          <%= f.input :caption %>
          <%= f.input :picture %>
          <br>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit "Submit", class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>

    </div>
  </div>
</div>

<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1 class="pull-left">Photos</h1>

  <!-- Photo Form -->

  <% if current_user && current_user == @place.user %>
    <button type="button" class="btn btn-primary btn-lg pull-right" data-toggle="modal" data-target="#myModal2">
      Add a Picture
    </button>
  <% end %>

  <div class="clear"></div>
  <br>
  <br>

  <% @place.photos.each do |photo| %>
    <div class="col-xs-12 col-sm-6">
      <figure>
        <%= image_tag photo.picture %>
        <figcaption>
          <%= photo.caption %>
        </figcaption>
      </figure>
      <br>
    </div>
  <% end %>


</div>



<div class="clear"></div>

<!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Add a comment</h4>
      </div>
      <div class="modal-body">
        <!-- the comments are now wired up underneath the place area in the routes.rb file -->
        <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
          <%= f.input :message %>
          <!-- Dropdown menu -->
          <%= f.input :rating, as: :select, collection: Comment::RATINGS %>
          <br>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit "Submit", class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>

    </div>
  </div>
</div>


<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1 class="pull-left">Comments</h1>

  <button type="button" class="btn btn-primary btn-lg pull-right" data-toggle="modal" data-target="#myModal">
    Add a comment
  </button>

  <div class="clear"></div>
  <br>

  <% @place.comments.each do |comment| %>
    <div class="col-xs-12 col-sm-6">
      <blockquote>
        <% if comment.humanized_rating.present? %>
          <b><%= comment.humanized_rating %></b> -
        <% end %>
        <%= comment.message %>
        <small><%= comment.user.email %></small>
      </blockquote>
    </div>
  <% end %>

</div>

app/views/users/show.html.erb
<div class="booyah-box">
  <div class="col-xs-4">
    <%= image_tag "user.png" %>    
  </div>

  <div class="col-xs-8">
    <h1> <%= @user.email %></h1>
    <h3> Member since: <%= @user.created_at.strftime("%B %d, %Y") %> </h3>
    <br>
    <h4>Total comments: <%= @user.comments.count %> </h4>
    <h4>Total five star reviews: <%= @user.comments.where(rating: '5_stars').count %> </h4>    
  </div>
  <div class="clear"></div>
</div>

<br><br>

<h1 class="text-center">My Comments</h1>
<div class="booyah-box">
  <% @user.comments.each do |comment| %>
    <div class="col-xs-12 col-sm-6">
      <h2 class="text-center"><%= link_to comment.place.name, place_path(comment.place) %></h2>
      <blockquote>
        <% if comment.humanized_rating.present? %>
          <b><%= comment.humanized_rating %></b> -
        <% end %>
        <%= comment.message %>
        <small><%= comment.user.email %></small>
      </blockquote>
    </div>
  <% end %>
  <div class="clear"></div>
</div>

<br><br>

<h1 class="text-center">My Places</h1>
<% @user.places.each do |place| %>
  <div class="booyah-box">
    <h1><%= link_to place.name, place_path(place) %></h1>
    <i><%= place.address %></i><br /> <br />
    <p><%= place.description %></p> <br /> 


    <% if place.comments.present? %>
      <div class="col-xs-12">
        <blockquote>
          <% if place.comments.last.humanized_rating.present? %>
            <b><%= place.comments.last.humanized_rating %></b> -
          <% end %>
          <%= place.comments.last.message %>
          <small><%= place.comments.last.user.email %></small>
        </blockquote>
      </div>
    <% end %>

    <% if place.photos.present? %>
      <div class="col-xs-12">
        <%= image_tag place.photos.first.picture %>
      </div>
    <% end %>

    <div class="clear"></div>
    <br>

    <% if place.user.present? %>
      <small> <%= place.user.email %> </small>
    <% end %>
  </div>

<% end %>